services:
  - type: web
    name: ypb
    runtime: manual
    plan: free
    region: oregon
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan view:cache
      php artisan route:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://ypb.onrender.com
      - key: APP_KEY
        generateValue: true
