services:
  - type: web
    name: ypb
    env: docker
    repo: https://github.com/priyanshjadav26/YPB
    branch: main
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false

jobs:
  - name: migrate-db
    type: manual
    env: docker
    repo: https://github.com/priyanshjadav26/YPB
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: php artisan migrate --force
